### ISSUE TITLE
[BUG] Show database name collation error From cPanel Mysql 8 To MariaDB

### ISSUE THREAD

**Issue by fredroo** [usmannasir/cyberpanel#1076]
**Describe the bug**
When run script to import cPanel Accounts show collation error unknown but don't show what domain, subdomain or database, I think maybe be impossible if you have a lot websites
ERROR 1273 (HY000) at line 1613: Unknown collation: 'utf8mb4_0900_ai_ci'

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. Open terminal and run this line below
2. /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/cPanelImporter.py --path /home/backup/accounts

**Expected behavior**
Show error unknown with name of database or domain or subdomain

**Screenshots**

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.3.4 

**Additional context**

**Comment by fredroo** [comment]
All websites after restoring show 404 but after fixing permissions with 
find foldername -type d -exec chmod 755 {} \;
find foldername -type f -exec chmod 644 {} \;

All Website is online right now

But all file managers show empty folders 

restore script create all websites like example.com folder in /home like /home/example.com/public_html

What is the right owner of folder /home/example.com and inside public_html is www-data:www-data or root:root

**Comment by usmannasir** [comment]
If you click "Fix Permissions" from file manager, it will restore the correct permissions for everything.

**Comment by fredroo** [comment]
@usmannasir I found the problem, the import script did not create domain users, all domains are in root users, I found this because create a new domain, then took a look at the user and group with the command LS in the terminal, any chance you repair this in new versions to fix my problem? all domains right now is online, but with root user

**Comment by fredroo** [comment]
@usmannasir backup failed too, I think this is because not create a user for each domain in the right way, The import script creates websites but not the users for each website

**Comment by fredroo** [comment]
Solved, https://www.cyberciti.biz/faq/howto-move-migrate-user-accounts-old-to-new-server/ with this tutorial

![error-users-cyberpanel](https://github.com/usmannasir/cyberpanel/assets/6863089/a68b0d7a-8afe-473e-aeb1-c591bf322eb7)

before copy to old server is important remove users equals

**Comment by fredroo** [comment]
@usmannasir  
![image](https://github.com/usmannasir/cyberpanel/assets/6863089/6e834e90-3956-498e-8711-3c43cd1afcbc)

this is the version I used to import in DigitalOcean, but I don't know if in my server with the problem I use the User UBUNTU instead of ROOT

you can test if someone has the same problem, thanks for your time and patience
