### ISSUE TITLE
Unable to create website for Normal User

### ISSUE THREAD

**Issue by ertomedia** [usmannasir/cyberpanel#11]
I'm getting the following message when trying to create a new website under a Normal User,

> {"error_message": "Not enough privilege", "error": 1}

I'm using Cyber Panel v1.6 inside a CentOS 7 minimal OpenVZ VPS.

Thank you.

**Comment by usmannasir** [comment]
Creating website is removed from Normal user and replaced by child domains, more details : https://forums.cyberpanel.net/discussion/108/package-doesnt-not-showing-for-normal-user
