### ISSUE TITLE
[BUG] Brazil create a new website from registro.br - NS records wrong

### ISSUE THREAD

**Issue by fredroo** [usmannasir/cyberpanel#1204]
**To Reproduce**
What steps did you take when the issue occurred? 
1. Click on the "Websites" tab.
2. Click on "Create Website".
3. The site was created successfully but in Brazil, domains are created DNS like ns1.site.com.br ns2.site.com.br instead of the nameservers ns7.hostname.net and ns8.hostname.net
4. try editing in DNS records but only accept one record to domain hostname using cyberpanel and works normally dot net

**Expected behavior**
create NS ns7.site.net and create NS ns8.site.net
**Screenshots**
![370ed1bf-c40f-4af9-b525-08925f083b64](https://github.com/usmannasir/cyberpanel/assets/6863089/52dc92eb-ca63-4172-a805-1e0a35a39eae)

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
stable or 2.3.5 latest commit

**Additional context**
I Believe something changed in https://registro.br or cyberpanel for domains from Brazil

my server NS have two but both are the same ip

**Comment by usmannasir** [comment]
I did not understand your problem, can you explain a bit more ?

**Comment by fredroo** [comment]
In domains from Brazil until now, not tested with another, when you create a new website, the DNS records in the case ns, are ns1,yourwebsite.com.br ns2,yourwebsite.com.br instead ns7.myhost.net ns8.myhost.net as it should

@usmannasir

**Comment by usmannasir** [comment]
You can edit them and change them to whatever is needed by you. its not a bug. 

If you need help with setting up you can reach our support: https://platform.cyberpersons.com/

**Comment by fredroo** [comment]
@usmannasir as I use only one ip dedicated point to ns7 and ns8 I already try it

**Comment by fredroo** [comment]
@usmannasir I am still with problems when I create a new domain, my nameserver records don't work with a new domain, I think is a problem like ns1.domainhost.com.br ns2.domainhost.com.br are created to domains but don't work, with any global domain have the same problem, you think is only with me? what do you say about this?

my panel works very well with namehost.net:8090

but cyberpanel not create ns1.namehost.net ns2.namehost.net instead on truth are created ns1.mynedomain.com.br ns2.mynedomain.com.br

remember all domains cited here are only to exemplify

I not can update ns records because only one is updated

In my case, I use only one IPV4 for both NS records because I only have one in my dedicated
