### ISSUE TITLE
Do you have API doc

### ISSUE THREAD

**Issue by anxuanzi** [usmannasir/cyberpanel#34]
I need API doc, i saw the WHMCS module but i want the api doc then i can write other system's module

**Comment by anxuanzi** [comment]
Do you have it?

**Comment by usmannasir** [comment]
Will try to finalize a small document about current API.

**Comment by anxuanzi** [comment]
Can the API operating LiteSpeed?

**Comment by usmannasir** [comment]
Sorry? I did not understand.

**Comment by qtwrk** [comment]
He meant if it's possible to operate/control OLS via API

**Comment by anxuanzi** [comment]
Can it control all the things such as DNS and Email or LiteSpeed

**Comment by anxuanzi** [comment]
Sorry for my bad English

**Comment by usmannasir** [comment]
You can see this file for a general idea of what API can do for now: https://github.com/usmannasir/cyberpanel/blob/master/api/views.py

vhost Creation.
vhost Deletion.
Suspend Site.

And few more functions that you can see from the code.

**Comment by anxuanzi** [comment]
Thank u
I can help to sort out the API doc
I reference to WHMCS module

**Comment by usmannasir** [comment]
Right, qtwrk will send you the invite.
