### ISSUE TITLE
WHMCS Module Bug?

### ISSUE THREAD

**Issue by ToiletCommander** [usmannasir/cyberpanel#37]
Hey there.  
I just found that WHMCS Module for CyberPanel has a bug that "Terminate Account" does not work properly.  
As I went through the source code of Cyberpanel, I found that .py files in the api directory does not include user deletion. Can you go ahead and add this feature?  
I am willing to update the cyberpanel WHMCS module for you.

**Comment by usmannasir** [comment]
What if the same user owns other websites?

**Comment by ToiletCommander** [comment]
Thats not how WHMCS Works XD.  
Everytime a user in WHMCS system creates a website order, the module create a new user in CyberPanel.  
So I think deleting user API is necessary.

**Comment by usmannasir** [comment]
Correct, that is the case when the website is created via WHMCS.

However the same user is not limited to 1 website, the administrator can assign more websites to the same owner.

In this case, if we delete user along with the site from WHMCS API, it will also delete other websites.

**Comment by ToiletCommander** [comment]
That is right. So how can we solve this WHMCS problem?

**Comment by usmannasir** [comment]
If the user has only one site, we can remove the user along with deletion.

**Comment by ToiletCommander** [comment]
While you mention about deletion, do you mean delete the site or user?
Is there an API for deleting user? Thanks

**Comment by usmannasir** [comment]
I've added the possibility of deleting user when the website being deleted is the only website owned by that user, this only happens when the website is deleted from API: https://github.com/usmannasir/cyberpanel/blob/b30a1c56e5ecaed659f66a172b167fd73b302d13/api/views.py#L205

**Comment by ToiletCommander** [comment]
Thanks. Helps a lot! I will begin changing the WHMCS module now.

**Comment by usmannasir** [comment]
There are no changes from WHMCS side, but you can still do tests, run this command to install Github version

`sh <(curl https://mirror.cyberpanel.net/install-test.sh || wget -O - https://mirror.cyberpanel.net/install-test.sh)`

**Comment by ToiletCommander** [comment]
Thanks!

**Comment by CybroMujeeb** [comment]
Cyberpanel Whmcs Module Test Connection failed, but i can login directly from whmcs.
I have entered Ip address as host name , user id and password.
