### ISSUE TITLE
Bug: Child domain search returning website

### ISSUE THREAD

**Issue by istiak101** [usmannasir/cyberpanel#411]
In list child domain if you search "example" for all child domains that should return:

1. subdomain1.example.com
2. subdomain2.example.com
3. subdomain.exampledomain.com
4. subdomain.exampleabc.com

It is returning:

1. example.com
2. exampledomain.com
3. exampleabc.com

This should return child domains for that search term. Not website.

**Comment by usmannasir** [comment]
let me fix.

**Comment by usmannasir** [comment]
fixed.
