### ISSUE TITLE
Looks interesting - Docker image?

### ISSUE THREAD

**Issue by susinths** [usmannasir/cyberpanel#5]
This looks interesting, but sad it's locked into OpenLiteSpeed web server, isn't it?
Anyway, have you thought about providing Docker image for easier testing/deployment? 
What are the planned future features and/or limitations? 
- What Linux distros are supported?
- What DBs are supported?
- Does it support templates (for web server / php settings etc)?
- Apache .htaccess compatibility? 
- Is the web server fully configurable using command line tools and not limited to GUI stuff?

@usmannasir

**Comment by susinths** [comment]
Also, does it offer API for integration with billing systems?

**Comment by usmannasir** [comment]
Docker image is not available yet, we currently have WHMCS api and blest api is planned soon.

thanks

**Comment by usmannasir** [comment]
You could try this guide: https://forums.cyberpanel.net/discussion/200/docker-image-pre-built-and-guide-of-installing-cyberpanel-inside-docker#latest
