### ISSUE TITLE
Blacklisted domain??

### ISSUE THREAD

**Issue by Oburoni** [usmannasir/cyberpanel#960]
So I have install cyber panel, and i want to create de host where cyber panel is "Error message: Blacklisted domain." web01.blazenode.nl

What steps did you take when the issue occurred? 
Click on "Create Website."

**Screenshots**
![image](https://user-images.githubusercontent.com/68870134/187902060-c8311d5a-413f-43e5-9034-49203f2f319f.png)

**Operating system:**
Ubuntu 20.04 x86 64

**CyberPanel version:**
I have installed it today so the latest version, I think :)

**Comment by Oburoni** [comment]
issue half solved.
I make the link web01 to 1

**Comment by usmannasir** [comment]
Kindly check this guide: https://community.cyberpanel.net/t/error-message-blacklisted-domain/206
