### ISSUE TITLE
Does NOT support AlmaLinux 8

### ISSUE THREAD

**Issue by azvampyre** [usmannasir/cyberpanel#975]
./cyberpanel.sh: line 1627: cd: /usr/local/cyberpanel/install: No such file or directory
ls
>>CyberPanel CyberCP
cd CyberCP
ls
>>install.sh

sh install.sh

>>Unable to detect your OS... CyberPanel is supported on Ubuntu 18.04, CentOS 7.x and CloudLinux 7.x...

**Comment by usmannasir** [comment]
Just tested on Alma 8 works fine, kindly open request on our community with details of the bug you are facing.
